language: node_js
node_js:
  - 14
branches:
  only:
    - master
    - dev
    - v2-dev

notifications:
  email: false

jobs:
  include:
    - stage: "Lint"
      name: "Run EsLint"
      script: npm run lint
    - stage: "Test"
      name: "Run Unit Tests"
      script: npm run test
    - stage: "Build"
      name: "Build the Library"
      script: npm run build
